name: Main Build

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
